name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: riseofguy26/nuxt-movie-app2:latest
          build-args: |
            TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Latest Image
        run: docker pull riseofguy26/nuxt-movie-app2:latest

      - name: Stop & Remove Old Container
        run: docker rm -f nuxtContainer || true

      - name: Run New Container
        run: |
          docker run -d \
            -p 3000:80 \
            --name nuxtContainer \
            riseofguy26/nuxt-movie-app2:latest